@extends('layouts.admin')

@section('title', 'Import Quiz')

@section('breadcrumb')
    <a href="{{ route('admin.quizzes.index') }}" class="hover:text-gray-700 transition-colors">Quizzes</a>
    <span class="mx-2 text-gray-300">/</span>
    <span class="text-gray-700">Import JSON</span>
@endsection

@section('content')
<div class="mb-8 flex flex-wrap items-start justify-between gap-3">
    <div>
        <h1 class="cq-page-title">Import Quiz from JSON</h1>
        <p class="mt-1 text-sm text-gray-500">Upload a previously exported quiz file to create a new quiz with its questions and settings.</p>
    </div>
    <a href="{{ route('admin.quizzes.index') }}" class="cq-btn-secondary cq-btn-sm">
        <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
        </svg>
        Back to quizzes
    </a>
</div>

<div class="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(18rem,0.8fr)]">
    <div class="cq-card p-6 sm:p-7">
        <form method="POST" action="{{ route('admin.import.store') }}" enctype="multipart/form-data" class="space-y-6">
            @csrf

            <div class="rounded-2xl border border-dashed {{ $errors->has('file') ? 'border-red-300 bg-red-50/50' : 'border-emerald-200 bg-emerald-50/40' }} p-6 sm:p-8">
                <div class="flex flex-col items-center text-center">
                    <div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-white text-emerald-600 shadow-sm ring-1 ring-emerald-100">
                        <svg class="h-7 w-7" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M12 11v8m0 0l-3-3m3 3l3-3"/>
                        </svg>
                    </div>
                    <h2 class="mt-4 text-lg font-semibold text-gray-900">Choose a quiz export file</h2>
                    <p class="mt-2 max-w-xl text-sm leading-relaxed text-gray-500">
                        Import accepts a single JSON file generated by ClassQuiz export. The uploaded quiz will be created as a new quiz under your account.
                    </p>
                </div>

                <div class="mt-6">
                    <label for="file" class="block text-sm font-medium text-gray-700 mb-2">
                        JSON file <span class="text-red-500">*</span>
                    </label>
                    <input
                        id="file"
                        type="file"
                        name="file"
                        accept=".json,application/json"
                        class="cq-field w-full file:mr-4 file:rounded-lg file:border-0 file:bg-emerald-600 file:px-4 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-emerald-700 {{ $errors->has('file') ? 'cq-field-error' : '' }}"
                    >
                    <p class="mt-2 text-xs text-gray-500">Maximum file size: 2 MB.</p>
                    @error('file')
                    <p class="mt-2 text-xs font-medium text-red-600">{{ $message }}</p>
                    @enderror
                </div>
            </div>

            <div class="flex flex-wrap items-center justify-end gap-3 border-t border-gray-100 pt-5">
                <a href="{{ route('admin.quizzes.index') }}" class="cq-btn-secondary">
                    Cancel
                </a>
                <button type="submit" class="cq-btn-primary">
                    <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M12 11v8m0 0l-3-3m3 3l3-3"/>
                    </svg>
                    Import quiz
                </button>
            </div>
        </form>
    </div>

    <div class="space-y-4">
        <div class="cq-card p-5">
            <h2 class="text-sm font-semibold uppercase tracking-wide text-gray-500">What Gets Imported</h2>
            <ul class="mt-4 space-y-3 text-sm text-gray-600">
                <li class="flex gap-3">
                    <span class="mt-1 h-2 w-2 shrink-0 rounded-full bg-emerald-500"></span>
                    Quiz title and description
                </li>
                <li class="flex gap-3">
                    <span class="mt-1 h-2 w-2 shrink-0 rounded-full bg-emerald-500"></span>
                    Questions, choices, tags, points, and order
                </li>
                <li class="flex gap-3">
                    <span class="mt-1 h-2 w-2 shrink-0 rounded-full bg-emerald-500"></span>
                    Question settings, feedback, and explanations
                </li>
            </ul>
        </div>

        <div class="cq-card p-5">
            <h2 class="text-sm font-semibold uppercase tracking-wide text-gray-500">Notes</h2>
            <div class="mt-4 space-y-3 text-sm leading-relaxed text-gray-600">
                <p>The imported quiz is created as a new quiz. It does not overwrite an existing quiz.</p>
                <p>If the file is malformed or incomplete, the import will be rejected before anything is saved.</p>
                <p>Use exported JSON files from this system for the safest results.</p>
            </div>
        </div>
    </div>
</div>
@endsection
